# -*- coding: utf-8 -*-

def getMessages():
    messages=[
        ('Alexs birthday','Hey, when you see Alex today, can you give him a BIIIIIIIIIG hug from me and say Mitch says Happy Birthday!? Thank you!',[1,4,8,8]),
        ('[Carpediem] LF1M ARTEMIS!',"Have you ever been on a spaceship? Come be on a spaceship in WH3!   *Artemis is a spaceship bridge simulator that’s pretty dope",[1,8,1,4]),
        ("On Duty","Hello RAs, You are on duty this weekend and I wanted to connect with you about some information that I thought would be helpful to know.   The CAB Halloween party has been moved to Saturday November 1st. The event will end at 2:00am, when the time change occurs and it becomes 1:00am. With the time change you should be doing your 3rd round at the time change when 2:00am becomes 1:00am. This will also correspond with the Halloween party letting out. Please know that you should be doing rounds in your area until your area is under control. If things are not calm in your area when completing your third round, you should do rounds until your area is under control.   If you have any questions please speak with your Area Director. You also have the Student Life On-Call to assist with anything over the weekend.   Have a quiet and enjoyable Halloween weekend!   Best, The Big Boss",[5,8,7,8]),
        ("[Carpediem] Last Call for Broomball","If you want to come play, meet in the WH1 antelounge in 15 minutes with athletic shoes, warm clothes and gloves.",[3,3,4,3]),
        ("Borrow your car?","This Wednesday (the 12th) I have an interview at AthenaHealth, and I need a way to get there!  I'm looking to either borrow a car, or get a ride there and back.  My interview is scheduled to be from 10:15 AM to 2:30 PM, and it takes ~30 minutes to get there.  Let me know if those times work for you/your car.  Compensation will, of course, be provided.",[3,1,9,8]),
        ("Lit Review Paper","Here’s my draft. It’s still missing a conclusion, but everything else is there! Thanks!",[8,9,8,8]),
        ("Re: Fencing","I didn't know Olin had a fencing team! Sounds fun! Love, Mom",[6,7,4,8]),
        ("Fwd: Lunch Date","I’m quite glad I slept through this! [Begin forwarded message] Love, Dad",[6,6,4,3]),
        ("Hi","<3",[10,10,7,8]),
        ("Sing in benefit show?","We weren't planning on providing any, but we could probably get a keyboard and someone to play it. What are you thinking of doing?",[7,5,9,8]),
        ("Team Dynamics","I'm really not happy with how you've been working on this team. If your lazyness and lack of effort continue, you will be terminated. --Brian Boss",[9,10,10,8]),
        ("Hi from Grandma","Hi Sunny! It's your grandma mildred! I've just figured out how to use this new thing called email! It's pretty groovy! Hope you're doing well! Love, Grandma",[8,4,7,8]),
        ("Bonefish & Tarpon Trust November Newsletter","Greetings!    Flats fisheries conservation is complicated. It involves guides, anglers, scientists, resource managers, science, conservation, economics, and education.  Perhaps most important is what connects all of these moving parts - communication. That's what makes the Bonefish & Tarpon Trust Symposium so important. Although we put a lot of effort into communication every day, the Symposium provides an opportunity that exists nowhere else - a collection of all of the moving parts in one venue for two days of communication. Previous symposia have received rave reviews, and we expect the same from the upcoming 5th International Bonefish & Tarpon Trust Symposium. Plus, the new Film and Art Festival on Friday night will open an entirely new avenue of communication that combines conservation and fishing. It promises to be exciting. I hope to see you there.  If you are unable to make it, you can still contribute to BTT's conservation efforts (the Symposium is, after all, also a fundraiser). The items from the silent auction are available online. So please take a look.   Finally, a big Thank You to all of the Symposium sponsors and auction item donors. They help make this important event possible. ",[2,1,2,3]),
        ("Holiday Party!","Join us Thanksgiving weekend to kick off an exciting holiday season, Pirate's Cove style.  There is something for every member of the family - kids, adults and pets!  Holiday parade, tree lighting, pictures with Santa, pet fashion show and much more!",[1,4,2,3]),
        ("It's been a while","Hey! It's been a while since we last spoke. How are you doing? Are you keeping your grades up? How's life? Are you still in a lot of clubs? Dan and I went out on the boats last weekend. We had a lot of fun. I remember when you and your mother used to join us for that. We had a good time. Especially the time you found the oyster that had the rock in it and you were convinced in was a pearl and you were going to be rich! You were so adorable! Hope you're doing well and your classes are still good. Keep up those grades! Sally",[8,6,9,8]),
        ("Disappointed","Good Morning All,   I asked that you send me the names and rooms of students who can show their room for the tour of the residence halls by last Wednesday at the latest. I am very disappointed that it is now Friday and I have not heard from any of you about this. I realize that this is a busy time in the semester for everyone, but you cannot be forgetting about you RA duties. I feel like our staff started off so strong and now many of you are taking this leadership position for granted. I hope that moving forward you will all show more dedication to this position and that  you all respond to my requests in a timely manner. I want to support each of you as students and RAs, but I need you to stay on top of RA tasks in order to provide that support.   Please get those names to me by 2pm today.   -Your Boss",[8,8,7,8]),
        ("Flight home","Definitely Philadelphia or BWI, later of the time choices",[10,8,7,8]),
        ("Coming home","I'm really excited to see you. It's been too long! Have a safe flight. I hear your Mom is going to drive you by our house on your way back. I'm looking forward to seeing you!",[8,7,8,8]),
        ("Important!!!","Sammy--Your dad and I are on the way to the vet to put Ross to sleep. He got hit by a car this morning. I called your phone, but you didn't answer. Call me, and I'll let you talk to him. --Mom",[10,10,10,8]),
        ("Meeting Wednesday","Can you meet in the dining hall at 6 on Wednesday to work on the project?",[8,7,10,8]),
        ("Burn Friday","Meet outside the OFAC room to help carry stuff at 9 if you want to burn! the stuff won't carry itself!",[2,3,7,8]),
        ("New Opportunity","It is my pleasure to inform you that you have been recommended by one of your professors to apply to be a Writing Center Peer Consultant.  Peer Consultants are specially trained students who work, for pay, in the Writing Center, helping members of the Babson community (primarily undergraduate students) with all aspects of their writing.  To become a Peer Consultant, you must complete a brief application (attached), turn in a writing sample, and complete an interview with the Director of the Writing Center.  If you are selected, you will then register for a 4-credit Spring 2015 course, ENG 3602: Practicum in Peer Consulting and Writing.  This course will be offered in Spring 2015 on Monday/Wednesday 3:25 - 5:00.  In May, those who have successfully completed the course will be asked to become Peer Consultants, beginning in Fall 2015.  You must currently be a sophomore or junior to apply.  Why go through this process?  Peer Consultants, as specially trained employees of Babson, are well-paid.  In addition, taking the course and working as a Peer Consultant gives you a chance to drastically improve your own writing, from process to product.  Finally, working as a Peer Consultant is a great resume-builder that distinguishes you as one of the best communicators on campus.  I invite you to investigate this opportunity by talking to current Peer Consultants, either by speaking to them informally or by making an appointment via Portal--Smart Tools--Writing Center Appointment.  Turn in all application materials to Prof. Carolyn Megan, Director of the Writing Center, Babson 205. Hand the materials to a Consultant or place your application located in the box in Babson 205.  The deadline for receipt of all written materials is Monday, October 27, 2014 at 3:00 PM.  You will be contacted by email to let you know whether or not you have been selected for an interview.  Thank you for your interest, and I hope to hear from you.  You should be honored to have been recommended--that very act placed you in a select crowd of students.  Please email me if you have any further questions.",[5,8,6,9]),
        ("Assignment 3","hello lovely people! Here is part 2 of the qtm hmwk. Let me know if there is anything that I need to fix ",[5,3,5,3]),
        ("Don't miss out!","A special message from Tony Shalhoub. We sat down with the Emmy-winning actor to talk about Happy Days, Brooke Adams’ performance as Winnie, and why Babson and Boston audiences will love this enigmatic show.",[2,3,1,2]),
        ("Today's Meeting","Sorry for the short notice, but I can't make today's meeting as I have a 2:30 flight to catch. Heading to New York for an alumni reception for the National Academy Foundation - naf.org/alumni<http://naf.org/alumni>.  Sorry again for the short notice!",[3,3,3,4])    
    ]
    return messages
